import type { Article, Category, Comment, FriendLink, GuestbookMessage, Tag } from "./types";

export const categories: Category[] = [
  { id: 1, name: "技术", slug: "tech", count: 8, sort: 30 },
  { id: 2, name: "随笔", slug: "essay", count: 5, sort: 20 },
  { id: 3, name: "年度总结", slug: "yearly-review", count: 3, sort: 10 },
  { id: 4, name: "生活", slug: "life", count: 3, sort: 5 },
];

export const tags: Tag[] = [
  { id: 1, name: "React", slug: "react", sort: 40 },
  { id: 2, name: "JavaScript", slug: "javascript", sort: 35 },
  { id: 3, name: "前端", slug: "frontend", sort: 30 },
  { id: 4, name: "生活", slug: "life", sort: 20 },
  { id: 5, name: "编程", slug: "coding", sort: 25 },
  { id: 6, name: "思考", slug: "thinking", sort: 15 },
  { id: 7, name: "设计", slug: "design", sort: 18 },
  { id: 8, name: "博客", slug: "blog", sort: 10 },
];

export const articles: Article[] = [
  {
    id: 1,
    title: "在春天的某个下午写代码",
    summary: "窗外的樱花正在盛开，我坐在电脑前敲打键盘，记录一点关于编程与生活的思考。",
    content:
      "这是一篇关于写代码、生活节奏和个人博客的 mock 文章。后续会接入 Go Gin 后端接口，并渲染真实 Markdown 内容。\n\n## 一点记录\n\n慢一点，把每个页面做得更适合长期使用。",
    cover: "/images/sakura-mountain.png",
    category: categories[1],
    tags: [tags[3], tags[4], tags[5]],
    status: "published",
    updatedAt: "2026-05-20",
    publishedAt: "2026-05-20",
    commentCount: 3,
    isTop: true,
  },
  {
    id: 5,
    title: "React 页面迁移到 Astro 的一点经验",
    summary: "从 v0 生成的 Next.js 页面里保留视觉语言，再把路由和组件重新放进 Astro 的结构里。",
    content: "这里是关于 React、Astro 和前端迁移的文章正文示例。",
    category: categories[0],
    tags: [tags[0], tags[2], tags[7]],
    status: "published",
    updatedAt: "2026-05-17",
    publishedAt: "2026-05-17",
    commentCount: 2,
    isTop: false,
  },
  {
    id: 6,
    title: "给个人博客做一个温柔的设计系统",
    summary: "玻璃、纸张感、大圆角和轻阴影不应该只是装饰，它们要让阅读变得更安静。",
    content: "这里是关于设计和博客视觉的文章正文示例。",
    cover: "/images/sakura-mountain.png",
    category: categories[0],
    tags: [tags[6], tags[7], tags[2]],
    status: "published",
    updatedAt: "2026-05-09",
    publishedAt: "2026-05-09",
    commentCount: 1,
    isTop: true,
  },
  {
    id: 7,
    title: "我的 2025 年度总结",
    summary: "回顾过去一年里完成的项目、学到的技术，以及那些慢慢改变生活节奏的小决定。",
    content: "这里是年度总结文章正文示例。",
    category: categories[2],
    tags: [tags[3], tags[5]],
    status: "published",
    updatedAt: "2026-01-01",
    publishedAt: "2026-01-01",
    commentCount: 0,
    isTop: false,
  },
  {
    id: 2,
    title: "Go Gin 博客接口整理",
    summary: "把博客后端的游客接口和管理员接口分离后，前端可以更清晰地组织页面。",
    content: "这里是 Go Gin 文章正文示例。",
    cover: "/images/sakura-mountain.png",
    category: categories[0],
    tags: [tags[4], tags[7]],
    status: "draft",
    updatedAt: "2026-05-18",
    isTop: false,
  },
  {
    id: 3,
    title: "一次安静的重构计划",
    summary: "不是所有重构都需要轰轰烈烈，有时候只是把路径、接口和页面慢慢放回正确的位置。",
    content: "这里是文章正文示例。",
    category: categories[0],
    tags: [tags[3]],
    status: "offline",
    updatedAt: "2026-05-12",
    isTop: false,
  },
  {
    id: 4,
    title: "旧文章归档测试",
    summary: "这是一篇用于回收站视图的 mock 文章。",
    content: "这里是已删除文章正文示例。",
    category: categories[2],
    tags: [tags[3]],
    status: "deleted",
    updatedAt: "2026-04-28",
    deleted: true,
    isTop: false,
  },
];

export const comments: Comment[] = [
  {
    id: 1,
    articleId: 1,
    articleTitle: "在春天的某个下午写代码",
    nickname: "Moon",
    email: "moon@example.com",
    website: "https://example.com",
    content: "这个博客的氛围很舒服，期待后续文章。",
    createdAt: "2026-05-21 20:18",
    browser: "Chrome",
    os: "macOS",
    ip: "203.0.113.12",
  },
  {
    id: 2,
    articleId: 1,
    articleTitle: "在春天的某个下午写代码",
    nickname: "Reader",
    email: "reader@example.com",
    content: "评论区表单可以再加一个 Markdown 开关。",
    createdAt: "2026-05-22 09:12",
    deleted: true,
    browser: "Safari",
    os: "iOS",
    ip: "203.0.113.24",
  },
  {
    id: 3,
    articleId: 1,
    articleTitle: "在春天的某个下午写代码",
    nickname: "Haruka",
    email: "haruka@example.com",
    website: "https://haruka.example.com",
    content: "喜欢这句“慢一点”，感觉很适合个人博客。",
    createdAt: "2026-05-22 12:40",
    browser: "Edge",
    os: "Windows",
    ip: "203.0.113.31",
  },
  {
    id: 4,
    articleId: 5,
    articleTitle: "React 页面迁移到 Astro 的一点经验",
    nickname: "Astro Fan",
    email: "astro@example.com",
    content: "Astro 的 islands 模式用在博客上确实舒服。",
    createdAt: "2026-05-18 19:22",
    browser: "Chrome",
    os: "Windows",
    ip: "198.51.100.9",
  },
  {
    id: 5,
    articleId: 5,
    articleTitle: "React 页面迁移到 Astro 的一点经验",
    nickname: "River",
    email: "river@example.com",
    website: "https://river.example.com",
    content: "后续可以写一篇组件拆分的记录。",
    createdAt: "2026-05-19 08:51",
    browser: "Firefox",
    os: "Linux",
    ip: "198.51.100.15",
  },
  {
    id: 6,
    articleId: 6,
    articleTitle: "给个人博客做一个温柔的设计系统",
    nickname: "Design Notes",
    email: "design@example.com",
    content: "这个配色很干净，阅读压力比较低。",
    createdAt: "2026-05-10 21:03",
    deleted: true,
    browser: "Chrome",
    os: "macOS",
    ip: "192.0.2.22",
  },
];

export const guestbookMessages: GuestbookMessage[] = [
  {
    id: "g-1",
    nickname: "Sora",
    email: "sora@example.com",
    website: "https://example.com",
    content: "路过留言，愿这里一直保持安静和漂亮。",
    createdAt: "2026-05-20 15:30",
    browser: "Chrome",
    browserVersion: "147.0.0.0",
    os: "macOS",
    device: "Desktop",
    ip: "203.0.113.45",
    location: "Japan",
  },
  {
    id: "g-2",
    nickname: "Vanilla Reader",
    email: "reader@example.com",
    content: "喜欢这张樱花雪山的背景。",
    createdAt: "2026-05-19 11:05",
    deleted: true,
    browser: "Safari",
    browserVersion: "18.2",
    os: "iOS",
    device: "Mobile",
    ip: "203.0.113.48",
    location: "China / Guangdong",
  },
  {
    id: "g-3",
    nickname: "Mika",
    email: "mika@example.com",
    website: "https://mika.example.com",
    content: "留言板的玻璃质感很温柔。",
    createdAt: "2026-05-22 10:16",
    browser: "Edge",
    browserVersion: "126.0",
    os: "Windows",
    device: "Desktop",
    ip: "198.51.100.33",
    location: "China / Shanghai",
    replyTo: {
      id: "g-1",
      nickname: "Sora",
    },
  },
  {
    id: "g-4",
    nickname: "Lin",
    email: "lin@example.com",
    content: "这种安静的页面很适合慢慢读。",
    createdAt: "2026-05-22 21:24",
    browser: "Firefox",
    browserVersion: "128.0",
    os: "Linux",
    device: "Desktop",
    ip: "192.0.2.40",
    location: "Tokyo",
  },
];

export const friendLinks: FriendLink[] = [
  { id: 1, name: "Example Blog", url: "https://example.com", logo: "", sort: 10, status: 1 },
  { id: 2, name: "Frontend Notes", url: "https://frontend.example.com", logo: "", sort: 8, status: 1 },
];
