// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/admin/articles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员分页获取后台文章列表，支持状态、删除状态、分类和关键词筛选。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/article"
                ],
                "summary": "获取后台文章列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "文章状态，-1 全部，0 草稿，1 发布，2 下架",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "删除状态，-1 全部，0 未删除，1 已删除",
                        "name": "is_deleted",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分类 ID，0 表示全部",
                        "name": "category_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"list\\\":[],\\\"total\\\":0,\\\"page\\\":1,\\\"size\\\":10},\\\"msg\\\":\\\"获取后台文章列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"文章状态参数错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取后台文章列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/articles/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员创建文章，文章初始状态由业务逻辑设置。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/article"
                ],
                "summary": "创建文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建文章请求体。需要先准备 category_id 和 tag_ids，示例会创建一篇草稿文章",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"id\\\":1},\\\"msg\\\":\\\"创建文章成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数格式错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"创建文章失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/articles/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员按文章 ID 删除文章。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/article"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"删除文章成果\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"文章ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"删除文章失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/articles/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员按文章 ID 更新文章内容和标签。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/article"
                ],
                "summary": "更新文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新文章请求体。需要先准备 article_id、category_id 和 tag_ids",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"id\\\":1},\\\"msg\\\":\\\"修改文章成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"文章ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"修改文章失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/articles/updateStatus/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员发布或下架文章。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/article"
                ],
                "summary": "更新文章状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文章 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "文章状态请求体。status 示例：1 表示发布，2 表示下架",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateArticleStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"文章发布成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"文章状态不合法,只允许发布或下架\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"更新文章状态失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/categories": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员获取全部分类列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/category"
                ],
                "summary": "获取后台分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":[],\\\"msg\\\":\\\"获取分类列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取分类列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/categories/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员创建文章分类。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/category"
                ],
                "summary": "创建分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建分类请求体。category_name 示例：Go 后端；slug 示例：go-backend；sort 示例：10",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"id\\\":1},\\\"msg\\\":\\\"创建分类成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数格式错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"创建分类失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/categories/{id}/sort": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新分类排序值。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/category"
                ],
                "summary": "更新分类排序",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分类排序请求体。sort 示例：20",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateCategorySortRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"更新分类排序成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"分类ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"更新分类排序失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/categories/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新分类启用状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/category"
                ],
                "summary": "更新分类状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分类状态请求体。status 示例：1 表示启用，0 表示停用",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateCategoryStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"更新分类状态成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"分类ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"更新分类状态失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/comments/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员按评论 ID 删除评论。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/comment"
                ],
                "summary": "删除评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "评论 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"删除评论成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"删除评论失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/friendlinks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员分页获取全部友链。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/friendlink"
                ],
                "summary": "获取后台友链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"links\\\":[],\\\"total\\\":0,\\\"page\\\":1,\\\"size\\\":10},\\\"msg\\\":\\\"获取成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取友链失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/friendlinks/add": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员创建友链。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/friendlink"
                ],
                "summary": "创建友链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建友链请求体。name 示例：Example Blog；url 示例：https://example.com；status 示例：1",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateFriendLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"创建成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"创建失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/friendlinks/{id}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员按友链 ID 删除友链。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/friendlink"
                ],
                "summary": "删除友链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "友链 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"删除成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"删除失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/friendlinks/{id}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新友链。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/friendlink"
                ],
                "summary": "更新友链",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "友链 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新友链请求体。id 需要和 path 中的友链 ID 保持一致",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateFriendLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"更新成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"更新失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/login": {
            "post": {
                "description": "管理员使用用户名和密码登录，成功后返回 JWT token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "description": "管理员登录请求体。username 示例：admin；password 示例：123456",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AdminLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"登录成功\\\",\\\"data\\\":{\\\"token\\\":\\\"xxx\\\",\\\"username\\\":\\\"admin\\\",\\\"userID\\\":1}}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数格式错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"Token生成失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "已登录管理员修改密码。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "修改管理员密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改密码请求体。old_password 示例：123456；new_password 示例：654321",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"密码修改成功，请重新登录\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数校验失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "示例：{\\\"code\\\":401,\\\"msg\\\":\\\"旧密码错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/register": {
            "post": {
                "description": "注册管理员账号，当前路由未加鉴权。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "管理员注册",
                "parameters": [
                    {
                        "description": "管理员注册请求体。username 示例：admin；password 示例：123456",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AdminRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"Welcome!\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数校验失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "409": {
                        "description": "示例：{\\\"code\\\":409,\\\"msg\\\":\\\"用户名已被注册\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/tag/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员创建文章标签。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/tag"
                ],
                "summary": "创建标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建标签请求体。tag_name 示例：Gin；slug 示例：gin；sort 示例：10",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"id\\\":1},\\\"msg\\\":\\\"创建标签成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数格式错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"创建标签失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/tag/{id}/sort": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新标签排序值。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/tag"
                ],
                "summary": "更新标签排序",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "标签排序请求体。sort 示例：20",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateTagSortRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"更新标签排序成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"标签ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"更新标签排序失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/tag/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员更新标签启用状态。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/tag"
                ],
                "summary": "更新标签状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "标签状态请求体。status 示例：1 表示启用，0 表示停用",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateTagStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"更新标签状态成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"标签ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"更新标签状态失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/tags": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "管理员获取全部标签列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/tag"
                ],
                "summary": "获取后台标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":[],\\\"msg\\\":\\\"获取标签列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取标签列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/admin/username": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "已登录管理员修改用户名。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "修改管理员用户名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "修改用户名请求体。old_password 示例：123456；new_username 示例：newadmin",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.UpdateUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"msg\\\":\\\"用户名修改成功，请重新登录\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数校验失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "示例：{\\\"code\\\":401,\\\"msg\\\":\\\"用户未登录\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/articles/search": {
            "get": {
                "description": "根据关键词分页搜索已发布且未删除的文章。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "搜索文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"list\\\":[],\\\"total\\\":0,\\\"page\\\":1,\\\"size\\\":10},\\\"msg\\\":\\\"搜索成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"搜索文章失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/articles/timeline": {
            "get": {
                "description": "分页获取已发布且未删除的文章时间轴列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "获取文章时间轴",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"list\\\":[],\\\"total\\\":0},\\\"msg\\\":\\\"获取文章时间轴成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取文章时间轴失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/articles/{id}": {
            "get": {
                "description": "根据文章 ID 获取已发布且未删除的文章详情。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "获取文章详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"id\\\":1,\\\"title\\\":\\\"标题\\\"},\\\"msg\\\":\\\"查询成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"ID格式错误，请输入数字\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"查询失败或文章不存在\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/categories": {
            "get": {
                "description": "获取启用状态的分类列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "category"
                ],
                "summary": "获取前台分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "无业务参数",
                        "name": "unused",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":[],\\\"msg\\\":\\\"获取分类列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取分类列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/categories/{id}/articles": {
            "get": {
                "description": "根据分类 ID 分页获取已发布且未删除的文章列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article/category"
                ],
                "summary": "按分类获取文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"list\\\":[],\\\"total\\\":0},\\\"msg\\\":\\\"获取文章列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"分类ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取文章列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/cmments/get": {
            "get": {
                "description": "根据评论目标类型和目标 ID 分页获取评论列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "获取评论",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "目标类型，1 文章，2 留言板",
                        "name": "target_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "目标 ID",
                        "name": "target_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"list\\\":[],\\\"total\\\":0,\\\"page\\\":1,\\\"page_size\\\":10},\\\"msg\\\":\\\"获取评论成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取评论失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/comments/add": {
            "post": {
                "description": "添加文章评论或留言板评论。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "添加评论",
                "parameters": [
                    {
                        "description": "评论请求体。文章评论 target_type 示例：1；留言 target_type 示例：2，留言示例可参考 CreateMessageRequest 字段",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"id\\\":1},\\\"msg\\\":\\\"评论成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"参数错误\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"添加评论失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/friendlinks": {
            "get": {
                "description": "分页获取启用状态的友链。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friendlink"
                ],
                "summary": "获取前台友链",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"links\\\":[],\\\"total\\\":0,\\\"page\\\":1,\\\"size\\\":10},\\\"msg\\\":\\\"获取成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取友链失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/tags": {
            "get": {
                "description": "获取启用状态的标签列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tag"
                ],
                "summary": "获取前台标签",
                "parameters": [
                    {
                        "type": "string",
                        "description": "无业务参数",
                        "name": "unused",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":[],\\\"msg\\\":\\\"获取标签列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取标签列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/tags/{id}/articles": {
            "get": {
                "description": "根据标签 ID 分页获取已发布且未删除的文章列表。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article/tag"
                ],
                "summary": "按标签获取文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "示例：{\\\"code\\\":200,\\\"data\\\":{\\\"list\\\":[],\\\"total\\\":0},\\\"msg\\\":\\\"获取标签文章列表成功\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "示例：{\\\"code\\\":400,\\\"msg\\\":\\\"标签ID不合法\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "示例：{\\\"code\\\":500,\\\"msg\\\":\\\"获取标签文章列表失败\\\"}",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AdminLoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "controllers.AdminRegisterRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6,
                    "example": "123456"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "admin"
                }
            }
        },
        "controllers.CreateArticleRequest": {
            "type": "object",
            "required": [
                "category_id",
                "content",
                "cover_url",
                "is_top",
                "summary",
                "title"
            ],
            "properties": {
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "type": "string",
                    "example": "这里是文章正文内容，包含 Gin、GORM 和 MySQL 的实践记录。"
                },
                "cover_url": {
                    "type": "string",
                    "example": "https://example.com/cover.jpg"
                },
                "is_top": {
                    "type": "integer",
                    "example": 0
                },
                "summary": {
                    "type": "string",
                    "example": "这是一篇关于 Go 后端开发的文章摘要"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "我的第一篇博客"
                }
            }
        },
        "controllers.CreateCategoryRequest": {
            "type": "object",
            "required": [
                "category_name"
            ],
            "properties": {
                "category_name": {
                    "type": "string",
                    "example": "Go 后端"
                },
                "slug": {
                    "type": "string",
                    "example": "go-backend"
                },
                "sort": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "controllers.CreateCommentRequest": {
            "type": "object",
            "required": [
                "content",
                "nickname",
                "target_type"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "example": "这是一条 Apifox 测试评论"
                },
                "email": {
                    "type": "string",
                    "example": "tester@example.com"
                },
                "nickname": {
                    "type": "string",
                    "example": "Apifox Tester"
                },
                "parent_id": {
                    "type": "integer",
                    "example": 0
                },
                "target_id": {
                    "type": "integer",
                    "example": 1
                },
                "target_type": {
                    "type": "integer",
                    "example": 1
                },
                "website": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "controllers.CreateFriendLinkRequest": {
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "logo": {
                    "type": "string",
                    "example": "https://example.com/logo.png"
                },
                "name": {
                    "type": "string",
                    "example": "Example Blog"
                },
                "sort": {
                    "type": "integer",
                    "example": 10
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "controllers.CreateTagRequest": {
            "type": "object",
            "required": [
                "slug",
                "sort",
                "tag_name"
            ],
            "properties": {
                "slug": {
                    "type": "string",
                    "example": "gin"
                },
                "sort": {
                    "type": "integer",
                    "example": 10
                },
                "tag_name": {
                    "type": "string",
                    "example": "Gin"
                }
            }
        },
        "controllers.UpdateArticleRequest": {
            "type": "object",
            "required": [
                "category_id",
                "content",
                "cover_url",
                "is_top",
                "summary",
                "title"
            ],
            "properties": {
                "category_id": {
                    "type": "integer",
                    "example": 1
                },
                "content": {
                    "type": "string",
                    "example": "这里是更新后的文章正文内容。"
                },
                "cover_url": {
                    "type": "string",
                    "example": "https://example.com/cover-updated.jpg"
                },
                "is_top": {
                    "type": "integer",
                    "example": 1
                },
                "summary": {
                    "type": "string",
                    "example": "这是一篇更新后的 Go 后端开发文章摘要"
                },
                "tag_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "我的第一篇博客 - 已更新"
                }
            }
        },
        "controllers.UpdateArticleStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "要用指针，不然传0可能会认为没传，导致格式错误",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.UpdateCategorySortRequest": {
            "type": "object",
            "required": [
                "sort"
            ],
            "properties": {
                "sort": {
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "controllers.UpdateCategoryStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.UpdateFriendLinkRequest": {
            "type": "object",
            "required": [
                "id",
                "name",
                "url"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "logo": {
                    "type": "string",
                    "example": "https://example.com/logo-updated.png"
                },
                "name": {
                    "type": "string",
                    "example": "Example Blog Updated"
                },
                "sort": {
                    "type": "integer",
                    "example": 20
                },
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com"
                }
            }
        },
        "controllers.UpdatePasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 6,
                    "example": "654321"
                },
                "old_password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "controllers.UpdateTagSortRequest": {
            "type": "object",
            "required": [
                "sort"
            ],
            "properties": {
                "sort": {
                    "type": "integer",
                    "example": 20
                }
            }
        },
        "controllers.UpdateTagStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.UpdateUsernameRequest": {
            "type": "object",
            "required": [
                "new_username",
                "old_password"
            ],
            "properties": {
                "new_username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "newadmin"
                },
                "old_password": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MyBlog API",
	Description:      "Go Gin personal blog backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
